jupyter-server/jupyter-resource-usage

setup.py

Running `jupyter nbextension install --py nbresuse` expected to find main.js in /opt/conda/lib/python3.5/site-packages/nbresuse/static, but main.js was in /opt/conda/share/jupyter/nbextensions/nbresuse/. With the above change, the nbextension command succeeds.

Distribute static files via package_data

---

nbresuse/handlers.py

If the memory limit isn't set, the server extension raises an exception by doing `int(None`). This fixes it.

Handle case of memory limit not set.

---

nbresuse/static/main.js
setup.py

- Don't poll in background, since user does not see it
- Poll instantly once page is foregrounded
This should reduce the number of /metrics requests massively,
with minimal interruption to user experience.

Don't poll server when page is not active

---

nbresuse/__init__.py
nbresuse/metrics.py
nbresuse/prometheus.py
nbresuse/static/main.js

Not sure whether this is something you would want to include in the extension, but since right now the extension overwrites prometheus metrics I wanted to fix that.

report the memory usage metrics as prometheus metrics

---

README.md
azure-pipelines.yml
nbresuse/metrics.py
nbresuse/tests/test_basic.py
nbresuse/utils.py
setup.cfg
setup.py

This PR does a few things
- sets up testing for python3.7 on linux/osx/windows
- just did this on my account, we'll need to set it up for the main
- do we want to add more python versions?
- pins `psutil` and `notebook` dependencies
- `autopep8`'d for `flake8` compatibility
- adding test folder, some first tests
- adds testing, coverage, license, and version badges to the readme (need to point away from my azure as well)

Setting up testing/a few cleanup items

---

MANIFEST.in

This came up while packaging `nbresuse` for conda here: https://github.com/conda-forge/staged-recipes/pull/10854
We can bundle the license in the sdist to it wouldn't need to the copied into the feedstock anymore.

Include LICENSE

---

README.md

Fixes #29.
This is mostly intended to the consumers of the `/metrics` endpoint, as the current notebook extension doesn't show the CPU usage yet.

Add section about CPU usage to the README

---

.gitignore
README.md
nbresuse/metrics.py
nbresuse/prometheus.py
nbresuse/static/main.js
setup.py

Try to make `psutil` import optional. Still need to implement fronted fallback behavior if no `psutil` is found. (Or rather, need to better understand how JupyterLab statusbar looks for NBResuse output, to make sure that NBResuse "does nothing" in the way that JupyterLab expects when psutil is not installed.)

Make psutil optional dependency of NBResuse

---

CONTRIBUTING.md
nbresuse/__init__.py
nbresuse/metrics.py
nbresuse/prometheus.py
setup.py

First change is to make CPU limit also callable, and thus have almost identical patterns for memory and CPU metrics. Next step is to abstract and generalize those patterns, to allow for potentially arbitrary `psutil` metrics to be tracked. Third step is to begin to allow the metrics which are tracked to be controlled via the configurations/settings file.
Using these it should soon be possible to track network i/o with NBResuse, compare the [`psutil` documentation](https://psutil.readthedocs.io/en/latest/).
For system-wide metrics, psutil offers the categories of:
- CPU metrics
- Memory metrics
- Disk metrics
- Network metrics
- Sensor metrics
- Boot time and users (not sure if want/need to include that via NBResuse, but we maybe could)
For process-specific metrics, `psutil` offers the …

Make NBResuse more flexible.

---

.gitignore
.pre-commit-config.yaml

Add a couple of extra files to exclude in the gitignore.
Also fixing the pre-commit hook so it doesn't fail locally with other versions of Python than 3.6.

Fix pre-commit, extend gitignore

---

CONTRIBUTING.md
README.md
nbresuse/__init__.py
nbresuse/api.py
nbresuse/static/main.js
nbresuse/tests/test_basic.py
setup.py

This solves yuvipanda#36
Have to raise PR on jupyterlab statusbar-extension to change api call to /api/nbresuse/v1 once this PR is merged.
Once this is done, then we can merge yuvipanda#41 and release a new version to PyPi.

Adding support for jupyterlab statusbar-extension #36

---

nbresuse/api.py

Follow-up to https://github.com/yuvipanda/nbresuse/pull/45 which restored the API endpoint.
`cpu_percent` was referred as an attribute instead of local variable.

Fix handling of cpu percent in the API endpoint

---

nbresuse/__init__.py
nbresuse/config.py
nbresuse/static/main.js
setup.py

/metrics is where notebook server publishes prometheus metrics.
Currently, if nbresuse is installed, it's impossible to get
prometheus metrics out of running notebooks.
Just removing /metrics caused issues with third-party
code (https://github.com/yuvipanda/nbresuse/issues/36) that depended
on the JSON API from the endpoint, and so was reverted.
Instead, we 'soft' deprecate that endpoint.
1. Re-add /api/metrics/v1 endpoint, with exact same semantics as
/metrics. This is enabled unconditionally.
2. /metrics is also enabled by default, but can be turned off with
a notebook config. This allows admins who need prometheus metrics
to turn it on.
3. The bundled notebook extension will read from /api/metrics/v1
endpoint, so for those users things will 'just work'.
The path to removing /metrics …

Soft-deprecate /metrics endpoint

---

pyproject.toml
setup.py

Using `skip_if_exists` from `jupyter_packaging`.
This avoids rebuilding the assets if they already exist (for example in the source tarball).
Follow-up to the switch to `jupyter-packaging` from #69.

Skip building js assets if they already exist

---

jupyter_resource_usage/__init__.py
jupyter_resource_usage/api.py
jupyter_resource_usage/metrics.py
jupyter_resource_usage/prometheus.py
jupyter_resource_usage/tests/test_basic.py
setup.py

Clarify notebook/jupyter_server usage

---

jupyter_resource_usage/api.py

Follow-up to #93 
Trying the latest locally, there seems to be a couple of warnings related to having the `__del__` method:
```bash
Exception ignored in: <function ApiHandler.__del__ at 0x7ff024d01040>
Traceback (most recent call last):
File "/path/to/miniforge3/envs/jupyter-resource-usage-release/lib/python3.9/site-packages/jupyter_resource_usage/api.py", line 23, in __del__
super().__del__()
AttributeError: 'super' object has no attribute '__del__'
```
Looks like it should be fine to keep the previous behavior of having the executor as a class attribute.
cc @fcollonval

`executor` as ApiHandle class attribute

---

packages/labextension/yarn.lock

Which also updates the transitive `codemirror` dependency.

Update to 3.0.16 packages

---

packages/labextension/src/memoryUsage.tsx

Currently, the exponential backoff feature of the `Poll` class is not used since we never throw an error for a bad network request (e.g. a 404).
This is demonstrated by the fact that the frontend extension will keep hitting a 404 every 5 seconds if you disable the server extension.
As can be seen from the lumino code, we need to raise an exception to trigger the backoff code. Simply returning null doesn't do anything:
https://github.com/jupyterlab/lumino/blob/8567deefe4dd2c84b3bd22da5c8151941cd3b2db/packages/polling/src/poll.ts#L319-L329

Ensure we use backoff when request fails

---

jupyter_resource_usage/api.py

This MR fixes the issue that process collected in 
`all_processes = [cur_process] + cur_process.children(recursive=True)`
can be invalid in the next line when summing their memory resources.
`rss = sum([p.memory_info().rss for p in all_processes])`
The psutil documentation mentions this as a side-note:
["When accessing methods of this class always be prepared to catch NoSuchProcess and AccessDenied exceptions."](https://psutil.readthedocs.io/en/latest/index.html?#psutil.Process)
(this is not a theoretical issue - we could see this problem at our site and were therefore tracking it down to fix it)

catch psutil exceptions

---

jupyter_resource_usage/static/main.js

I added a brief extension to `main.js` to support displaying CPU utilization. I'm opening a PR in case there is interest in adding this functionality.
Happy to make changes to conform with style or extension usage.
This is how it looks in the browser:

Add CPU display to extension

---

CHANGELOG.md

Automated Changelog Entry for 0.6.1 on master
```
Python version: 0.6.1
npm version: @jupyter-server/jupyter-resource-usage-root: 0.1.0
npm workspace versions:
@jupyter-server/resource-usage: 0.6.1
```
After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | jupyter-server/jupyter-resource-usage  |
| Branch  | master  |
| Version Spec | 0.6.1 |
| Since | 0.6.0 |

Automated Changelog Entry for 0.6.1 on master

---

README.md
jupyter_resource_usage/config.py
jupyter_resource_usage/server_extension.py

Allow users to opt out of prometheus metrics

---

CHANGELOG.md

Automated Changelog Entry for 0.6.2 on master
```
Python version: 0.6.2
npm version: @jupyter-server/jupyter-resource-usage-root: 0.1.0
npm workspace versions:
@jupyter-server/resource-usage: 0.6.2
```
After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | jupyter-server/jupyter-resource-usage  |
| Branch  | master  |
| Version Spec | 0.6.2 |
| Since Last Stable | true |

Automated Changelog Entry for 0.6.2 on master

---

jupyter_resource_usage/static/main.js

I encountered what seems to be a bug in `jupyter-resource-usage`. The CPU percentage would not be updated, unless we were actually executing code. The result of this was that, after cells had completed and the CPU was idling (0% CPU usage), the displayed percentage would be stuck at the last non-zero value.
I traced the cause to [this line](https://github.com/jupyter-server/jupyter-resource-usage/blob/799343d066c9c828e079c3916ff1f8d155b0be1f/jupyter_resource_usage/static/main.js#L77). Most likely, the intend there was to make sure the CPU usage wasn't displayed if the API endpoint didn't register a CPU usage (i.e. if `data` didn't contain the `cpu_percent` key). However, `if (cpuPercent)` _also_ evaluates to `False` in Javascript if `cpuPercent=0`. That caused the lack of updates whenever …

Fix update at zero cpu

---

jupyter_resource_usage/__init__.py

Fix #91 by defining _load_jupyter_server_extension for further backward compatibility (see https://jupyter-server.readthedocs.io/en/latest/developers/extensions.html#migrating-an-extension-to-use-jupyter-server)
This PR replaces https://github.com/jupyter-server/jupyter-resource-usage/pull/134

Define _jupyter_server_extension_paths for backward compatibility

---

CHANGELOG.md

Automated Changelog Entry for 0.6.3 on master
```
Python version: 0.6.3
npm version: @jupyter-server/jupyter-resource-usage-root: 0.1.0
npm workspace versions:
@jupyter-server/resource-usage: 0.6.3
```
After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Draft Release | https://github.com/jupyter-server/jupyter-resource-usage/releases/tag/untagged-b72d415f8c3b298621fe  |
| Since Last Stable | true |

Automated Changelog Entry for 0.6.3 on master

---

README.md
jupyter_resource_usage/api.py
jupyter_resource_usage/static/main.js
packages/labextension/src/memoryUsage.tsx

Fixes https://github.com/jupyter-server/jupyter-resource-usage/issues/130

Use `pss` if available

---

jupyter_resource_usage/api.py
pyproject.toml

- handle get_msg being async _or not_, which I assume is sensitive to the combination of server and jupyter-client version(s)
- use async poller to avoid blocking while waiting for usage response, removes retries
Fixes:
```
[E 10:21:32.039 NotebookApp] Uncaught exception GET /api/metrics/v1/kernel_usage/get_usage/a03abaf0-9f33-49f9-8bf9-515f7e64c01f?1676542891240 (172.17.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:58133', method='GET', uri='/api/metrics/v1/kernel_usage/get_usage/a03abaf0-9f33-49f9-8bf9-515f7e64c01f?1676542891240', version='HTTP/1.1', remote_ip='172.17.0.1')
Traceback (most recent call last):
File "/srv/conda/envs/notebook/lib/python3.11/site-packages/tornado/web.py", line 1713, in _execute
result = await result
^^^^^^^^^^^^
File …
```

async fixes in kernel usage handler

---

jupyter_resource_usage/api.py
packages/labextension/package.json
packages/labextension/src/index.ts
packages/labextension/src/panel.ts
packages/labextension/src/tracker.ts
packages/labextension/src/types.ts
packages/labextension/src/widget.tsx
packages/labextension/style/base.css
packages/labextension/tsconfig.json
yarn.lock

Addresses https://github.com/jupyter-server/jupyter-resource-usage/issues/172#issuecomment-1412135781:
- clear kernel usage state when switching away by listening to `shell.activChanged` when in JupyterLab
- implement informative blank state in place of incorrect "not available" blanket statments
- handle timeout (preserve old usage for reference but grey them out and show that timeout occurred)
- check delayed replies to prevent displaying outdated state for a previous notebook
- support consoles (as a bonus)
Demonstration of the new behaviour:

Clear state when switching away, add blank state indicator

---

.github/workflows/build.yml
.github/workflows/tests.yml
README.md

Follow-up to the branch rename: https://github.com/jupyter-server/jupyter-resource-usage/issues/175

Rename references from `master` to `main`

---

jupyter_resource_usage/api.py

Stop all channels to allow ZMQContext to properly cleanup between calls

---

packages/labextension/src/index.ts

`IStatusBar` does not exist for Nb frontend and we should load the extension only for lab frontend.

Make `IStatusBar` optional for `resourceStatusPlugin`

---

packages/labextension/src/index.ts
packages/labextension/src/panel.ts
packages/labextension/src/tracker.ts
packages/labextension/src/widget.tsx

FIxes https://github.com/jupyter-server/jupyter-resource-usage/issues/204
The tracker now keeps track of the `currentWidget`. This is useful in the case of Notebook 7 where connecting to `currentChanged` might not be enough. Notebook 7 adds the notebook widget to the page very early, and the kernel usage component might be connecting to `tracker.currentChanged` *after* the `tracker.currentChanged` is emitted.
https://github.com/jupyter-server/jupyter-resource-usage/assets/591645/ac0075ca-12ad-44c4-bf7f-e4e5ac6cc4d7

Handle `currentWidget` in `KernelWidgetTracker`

---

jupyter_resource_usage/api.py
jupyter_resource_usage/config.py
packages/labextension/src/widget.tsx

This PR includes the changes to add a custom configuration to show or hide the Host CPU and Host Virtual Memory information (Issue: #209) . It is added as a config parameter, and can be set as:
`c.ResourceUseDisplay.show_host_usage=False` (if you want to hide the host usage info, default is set as True)
Follow the set up process from [`contributing.md`](https://github.com/jupyter-server/jupyter-resource-usage/blob/e6f707bd0b70b06d53ea68c411203de377d72767/CONTRIBUTING.md) or use the following commands:
```
conda create -n jupyter-resource-usage -c conda-forge python
conda activate jupyter-resource-usage
python -m pip install -e ".[dev]"
jupyter labextension develop . --overwrite
cd packages/labextension/
jlpm run build
jlpm run watch
jupyter lab --ResourceUseDisplay.show_host_usage=False …
```

Adds custom config to show/hide host usage info
